### PR TITLE
Run minimal vulnerabilities check in an unshare environment

### LINKED ISSUE #49: Reduce elevated privileges required to run preflight successfully when testing against a container image
When testing against a container image, the `HasMinimalVulnerabilitiesCheck` check makes a call out to oscap-podman, and it requires the ability to run a container as root. This test will fail if the runtime user cannot run a pod as root from what I can see.

We see this error if we run without elevated privileges

```
time="2021-07-09T13:36:57-05:00" level=error msg="unable to execute oscap-podman on the image: This script cannot run in rootless mode.\nvuln.html"
```

We're currently unable to control what checks are executed when calling preflight, which means we have to run the entire policy called with `sudo`. 

We need to identify a way to satisfy the HasMinimalVulnerabilitiesCheck's need for elevated privileges while still maintaining the ability to run the rest of the checks without elevated privileges.

### PR DESCRIPTION
**Pull request by bcrochet**
Besides making the minimal vulnerabilities check to run in an
unshare, this patch also changes the UnshareWithCheck signature to
simplify it, so that the "preflight check run" command does not have
to be specified each time, but it also specifies whether the check
should have the passed image mounted, then run the check, or just
have the check run in the unshare env.

Fixes #49

Signed-off-by: Brad P. Crochet <brad@redhat.com>

### CODE REVIEW

File: certification/internal/shell/has_minimal_vulns_unshare.go [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+	"fmt"
+	"regexp"
+	"strings"
+
+	"github.com/redhat-openshift-ecosystem/openshift-preflight/certification"
+	"github.com/redhat-openshift-ecosystem/openshift-preflight/certification/errors"
+	log "github.com/sirupsen/logrus"
+)
+
+// HasMinimalVulnerabilitiesCheck evaluates the image to confirm that only vulnerabilities
```
Comment (komish) [inline certification/internal/shell/has_minimal_vulns_unshare.go:13]: `HasMinimalVulnerabilitiesCheck` --> `HasMinimalVulnerabilitiesUnshareCheck`

File: certification/internal/shell/has_minimal_vulns_unshare.go [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+// below the Critical or Important severities, using oscap-podman and a corresponding
+// OVAL definition.
+type HasMinimalVulnerabilitiesUnshareCheck struct{}
+
+func (p *HasMinimalVulnerabilitiesUnshareCheck) Validate(image string) (bool, error) {
+	lines, err := p.getDataToValidate(image)
```
Comment (komish) [inline certification/internal/shell/has_minimal_vulns_unshare.go:19]: Nit: I somewhat dislike `getDataToValidate` as a method name because it isn't descriptive. I don't have a suggestion at the moment, and I know we use it in multiple places, but If you can think of a way to change this so that we can somewhat establish a shared context with the reader/developer reviewing or attempting to follow this code, that'd be great.

No need to change others, we can change them as we come across them.

File: certification/internal/shell/has_minimal_vulns_unshare.go [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+	if err != nil {
+		log.Debugf("Stdout: %s", lines)
+		return false, fmt.Errorf("%w: %s", errors.ErrImageScanFailed, err)
+	}
+
+	return p.validate(lines)
+}
+
+func (p *HasMinimalVulnerabilitiesUnshareCheck) getDataToValidate(image string) ([]string, error) {
```
Comment (komish) [inline certification/internal/shell/has_minimal_vulns_unshare.go:28]: I know it's not strictly required, but I believe we should start commenting these.

File: certification/internal/shell/podman.go [hunk 4]
```diff
@@ -284,14 +284,18 @@ func (pe PodmanCLIEngine) Unshare(env map[string]string, command ...string) (*cl
...
 	env := map[string]string{
 		"PATH":                 os.Getenv("PATH"),
 		"PREFLIGHT_EXEC_CHECK": check,
 		"PREFLIGHT_EXEC_IMAGE": image,
 	}
 
-	unshareReport, err := pe.Unshare(env, command...)
+	if mounted {
+		env["PREFLIGHT_EXEC_MOUNTED"] = fmt.Sprintf("%t", mounted)
+	}
```
Comment (komish) [inline certification/internal/shell/podman.go:296]: Why are we tracking the mounted state for this function? Is there logic somewhere that utilizes `PREFLIGHT_EXEC_MOUNTED` for some purpose?

I see it was added to the runtime.Config as well; trying to get a more complete picture but I'm missing it reviewing this.

**Review by komish — COMMENTED** [review]
Couple of questions and nits. LGTM for the most part, but I'll do some testing after I get more context.

EDIT: I hit "Comment" instead of "Request Changes", not sure how to change it so I'm leaving this as is!

File: certification/internal/shell/has_minimal_vulns_unshare.go (hunk 1 above)
Comment (bcrochet) [reply certification/internal/shell/has_minimal_vulns_unshare.go:13]: Fixed.

File: certification/internal/shell/has_minimal_vulns_unshare.go (hunk 2 above)
Comment (bcrochet) [reply certification/internal/shell/has_minimal_vulns_unshare.go:19]: I'll change this one to "scanImage", as that describes exactly what it is doing.

File: certification/internal/shell/podman.go (hunk 4 above)
Comment (bcrochet) [reply certification/internal/shell/podman.go:296]: This particular check does not require a mounted image. In fact, it will fail if it has one. So, I've added the ability for a check to designate whether it needs to have a mounted image or not. The environment variable then allows the "check run" command to signify whether it should instantiate a MountedEngine, or just a CheckEngine.

**Review by jomkz — APPROVED** [review]
/lgtm as I believe all of the comments have been addressed

**Review by komish — APPROVED** [review]
/lgtm
