### PR TITLE
Utilize built-in cache of crane library

### LINKED ISSUE #533: HasModifiedFiles fails intermittently since it tries to re-pull the image
## Bug Description
It seems that HasModifiedFiles check is re-pulling the image, so sometimes it fails.

## Version and Command Invocation
`1.1.0-beta6`

## Steps to Reproduce:
1) Run `check container gcr.io/kasten-images/frontend:4.5.11`

## Expected Result
I'd expect this image to always pass

## Actual Result
Sometimes you get the below error:

```
time="2022-03-30T19:57:32Z" level=info msg="certification library version 1.1.0-beta6 <commit: 2ebe87409fcc9333149511466fdb452ccb88ad44>"
time="2022-03-30T19:58:06Z" level=info msg="check completed: BasedOnUbi" result=PASSED
time="2022-03-30T19:58:13Z" level=info msg="check completed: HasModifiedFiles" ERROR="failed to extract tarball: failed to extract tarball: read tcp 172.17.0.2:59394->[142.250.72.176:443](http://142.250.72.176:443/): read: connection reset by peer" result="failed to extract tarball: failed to extract tarball: read tcp 172.17.0.2:59394->[142.250.72.176:443](http://142.250.72.176:443/): read: connection reset by peer"
time="2022-03-30T19:58:13Z" level=info msg="check completed: HasLicense" result=PASSED
time="2022-03-30T19:58:14Z" level=info msg="check completed: HasUniqueTag" result=PASSED
time="2022-03-30T19:58:14Z" level=info msg="check completed: LayerCountAcceptable" result=PASSED
time="2022-03-30T19:58:14Z" level=info msg="check completed: HasNoProhibitedPackagesMounted" result=PASSED
time="2022-03-30T19:58:14Z" level=info msg="check completed: HasRequiredLabel" result=PASSED
time="2022-03-30T19:58:14Z" level=info msg="check completed: RunAsNonRoot" result=PASSED
```

## Additional Context
We should always make sure we are using the image that's already been pulled and on disk locally.

### PR DESCRIPTION
**Pull request by bcrochet**
It was discovered that the HasModifiedFiles check was having to re-
pull the image under test. With this simple patch, we now utilize
the caching mechanism of crane, which has reduced the runtime of
HasModifiedFiles by an order of magnitude. It ends up being a
transparent change to the entire codebase, as the v1.Image passed
around in the ImageRef is an instance of the cached Image.

Fixes #533

Signed-off-by: Brad P. Crochet <brad@redhat.com>

### CODE REVIEW

File: certification/internal/engine/engine.go [hunk 1]
```diff
@@ -74,6 +75,13 @@ func (c *CraneEngine) ExecuteChecks(ctx context.Context) error {
 		}
 	}()
 
+	imageTarPath := path.Join(tmpdir, "cache")
+	if err := os.Mkdir(imageTarPath, 0o755); err != nil {
```
Comment (skattoju) [inline certification/internal/engine/engine.go:79]: looks like a typo here.. should be 0755 ?

Comment (skattoju) [reply certification/internal/engine/engine.go:79]: never mind looks like go fmt likes this better 😅

**Review by skattoju — APPROVED** [review]
