### PR TITLE
Fix HasModifiedFiles to check layer by layer

### LINKED ISSUE #846: Preflight does not detect the modification of the package and throw the warning or error in the results
## Bug Description
Infinidat certified an openstack image, they replaced a file via the command line  for this package python3-requests-2.20.0-2.1.el8_1.noarch in their  [dockerfile](https://github.com/Infinidat/cinder/commit/dc044c87791fb9d7caed7658d0cdd15d4520286c#diff-e58f4ed034f19f0d4c01795b2255eb8860f9a9bf478f90d4bb18e58d832197f8)
here is the command line :
 RUN curl -Ls [ https://raw.githubusercontent.com/psf/requests/v2.20.0/requests/__init__.py|https://raw.githubusercontent.com/psf/requests/v2.20.0/requests/_init.py] > /usr/lib/python3.6/site-packages/requests/init_.py

Whent they ran the preflight test for this image, it passed.
## Version and Command Invocation
1.4.1

## Steps to Reproduce:
1) build the image refer to the [dockerfile](https://github.com/Infinidat/cinder/commit/dc044c87791fb9d7caed7658d0cdd15d4520286c#diff-e58f4ed034f19f0d4c01795b2255eb8860f9a9bf478f90d4bb18e58d832197f8)
2) run the preflight tool with the image

## Expected Result
Test name: HasModifiedFiles -should fail
Policy guide: https://access.redhat.com/documentation/en-us/red_hat_software_certification/8.53/html-single/red_hat_openshift_software_certification_policy_guide/index#assembly-requirements-for-container-images_openshift-sw-cert-policy-introduction
*************************
Container images must not change content provided by Red Hat packages or layers except for files that both you or the customers can change, such as configuration files.

## Actual Result
The test results showed pass
 https://connect.redhat.com/projects/5f018e64ab0698a38db07f54/overview
sha256:1aebded18e9317ab3338d8f34ba8bcc5aebe98e566a51eae6775389dda059f68 -> pass

### PR DESCRIPTION
**Pull request by bcrochet**
* (almost) Complete rewrite of the check
* Ignore any path that starts with "etc/" or "var/"
* Ignore any RPM file that has config, doc, or config(missingok) flags
* Check each layer against the last, rather than all the flattened layers at once

Fixes #846

### CODE REVIEW

File: internal/engine/engine.go [hunk 1]
```diff
@@ -224,7 +224,7 @@ func (c *CraneEngine) ExecuteChecks(ctx context.Context) error {
 		checkElapsedTime := time.Since(checkStartTime)
 
 		if err != nil {
-			logger.WithValues("result", "ERROR", "err", err).Info("check completed", "check", check.Name())
+			logger.WithValues("result", "ERROR", "err", err.Error()).Info("check completed", "check", check.Name())
```
Comment (acornett21) [inline internal/engine/engine.go:227]: Isn't this a change from `main`?

Comment (komish) [reply internal/engine/engine.go:227]: Confirmed - Did something go sideways in a rebase?

**Review by komish — APPROVED** [review]
/lgtm

Still seeing only expected failures across my test 30 images or so.

File: internal/engine/engine.go (hunk 1 above)
Comment (bcrochet) [reply internal/engine/engine.go:227]: Actually, no. I think I had added that for something else. Won't hurt to leave it here for the moment. It will just get removed when we cherry-pick this back.

**Review by acornett21 — APPROVED** [review]
