### PR TITLE
Fixes #212 looking for artifacts dir but not found

### LINKED ISSUE #212: failed to create artifacts directory
## Bug Description
Preflight fails to run because it's looking for artifacts dir to be present.

## Version and Command Invocation
preflight version 0.0.0 <commit: d6389c597717aabbce381ab6a9c2047717d781eb>

## Steps to Reproduce:
(How can we reproduce this?)
1) ./preflight check operator <bundle image>

## Expected Result
Able to execute and display output

## Actual Result
Error: open artifacts/results.json: no such file or directory

The checks that will be executed are the following:
- ScorecardBasicSpecCheck
- ScorecardOlmSuiteCheck
- OperatorPackageNameIsUnique
- DeployableByOLM
- ValidateOperatorBundle

Usage:
  preflight check operator <url to Operator bundle image> [flags]
	
Flags:
  -h, --help   help for operator

time="2021-09-07T15:37:07Z" level=fatal msg="open artifacts/results.json: no such file or directory"

### PR DESCRIPTION
**Pull request by rocrisp**
The directory, "artifacts" needs to be there.
Fixed by creating the artifacts dir.

Fixes #212

### CODE REVIEW

File: cmd/utils.go [hunk 1]
```diff
@@ -59,3 +60,32 @@ func preRunConfig(cmd *cobra.Command, args []string) {
 		log.Info("config file not found, proceeding without it")
 	}
 }
+
```
Comment (samira-barouti) [inline cmd/utils.go:63]: I believe all these methods should go to util/file. There is a `ArtifactPath` method which has been implemented before that you can leverage.

File: cmd/utils.go [hunk 2]
```diff
@@ -59,3 +60,32 @@ func preRunConfig(cmd *cobra.Command, args []string) {
...
+func createArtifactsDir(artifactsDir string) (string, error) {
```
Comment (samira-barouti) [inline cmd/utils.go:64]: IMO, the artifact directory creation should be in preRunConfig() method

**Review by samira-barouti — CHANGES_REQUESTED** [review]

File: cmd/utils.go (hunk 1 above)
Comment (rocrisp) [reply cmd/utils.go:63]: Understood. However, but I think the methods in util/file are not exposed to be used. I could be wrong.

File: cmd/utils.go (hunk 2 above)
Comment (rocrisp) [reply cmd/utils.go:64]: Let me check.

File: cmd/utils.go (hunk 1 above)
Comment (samira-barouti) [reply cmd/utils.go:63]: They are exposed as public methods, so you can move stuffs there and reuse them in all checks

File: cmd/utils.go (hunk 2 above)
Comment (rocrisp) [reply cmd/utils.go:64]: I do see the preRunConfig() includes configuration and file creation. So I 
I can move both the dir and file creation of artifacts/results.json to preRunConfig() if that makes more sense.

Comment (samira-barouti) [reply cmd/utils.go:64]: In my opinion yes.. It would be great to have Brad's insight as well :) @bcrochet

Comment (rocrisp) [reply cmd/utils.go:66]: It looked like a mess to move the file creation and less of a mess to move the dir creation so I did the latter.

File: cmd/utils.go (hunk 1 above)
Comment (rocrisp) [reply cmd/utils.go:65]: make build
go build -o preflight -ldflags "-X github.com/redhat-openshift-ecosystem/openshift-preflight/version.commit=d6ea2fbf6472c69584c80ab197297761c714a67a -X github.com/redhat-openshift-ecosystem/openshift-preflight/version.version="0.0.0"" main.go
package command-line-arguments
	imports github.com/redhat-openshift-ecosystem/openshift-preflight/cmd
	cmd/utils.go:9:2: use of internal package github.com/redhat-openshift-ecosystem/openshift-preflight/certification/internal/utils/file not allowed
make: *** [Makefile:10: build] Error 1

https://stackoverflow.com/questions/59342373/use-of-internal-package-not-allowed

File: cmd/check_operator.go [hunk 3]
```diff
@@ -60,7 +60,6 @@ var checkOperatorCmd = &cobra.Command{
 			os.O_WRONLY|os.O_CREATE|os.O_TRUNC,
 			0600,
 		)
-
```
Comment (bcrochet) [inline cmd/check_operator.go:63]: This does not appear to be relevant to this patch.

File: cmd/utils.go [hunk 4]
```diff
@@ -58,4 +59,35 @@ func preRunConfig(cmd *cobra.Command, args []string) {
 	if !configFileUsed {
 		log.Info("config file not found, proceeding without it")
 	}
+
+	ArtifactPath()
```
Comment (bcrochet) [inline cmd/utils.go:63]: Instead of this, just use ArtifactPath() in check_container.go and check_operator.go where resultsFilenameWithExtension is being called.

File: cmd/utils.go (hunk 2 above)
Comment (bcrochet) [reply cmd/utils.go:66]: I made a comment above about where I believe it should occur.

File: cmd/utils.go (hunk 1 above)
Comment (bcrochet) [reply cmd/utils.go:65]: Perhaps move it to certification/utils/utils.go? Then the internal packages can utilize it, as well as the cmd package.

**Review by bcrochet — CHANGES_REQUESTED** [review]
Couple of questions and suggestions.

File: cmd/utils.go (hunk 1 above)
Comment (rocrisp) [reply cmd/utils.go:65]: Will do.

File: cmd/check_operator.go (hunk 3 above)
Comment (rocrisp) [reply cmd/check_operator.go:63]: Correct. No idea why it got in with the others.

File: certification/internal/engine/engine.go [hunk 5]
```diff
@@ -13,7 +13,7 @@ import (
 	"github.com/redhat-openshift-ecosystem/openshift-preflight/certification"
 	"github.com/redhat-openshift-ecosystem/openshift-preflight/certification/errors"
 	containerutils "github.com/redhat-openshift-ecosystem/openshift-preflight/certification/internal/utils/container"
-	fileutils "github.com/redhat-openshift-ecosystem/openshift-preflight/certification/internal/utils/file"
+	fileutils "github.com/redhat-openshift-ecosystem/openshift-preflight/certification/utils"
```
Comment (bcrochet) [inline certification/internal/engine/engine.go:16]: To avoid confusion this should be 'certutils'

File: certification/internal/utils/file/helper.go [hunk 6]
```diff
@@ -1,168 +0,0 @@
-package file
```
Comment (bcrochet) [inline certification/internal/utils/file/helper.go:1]: I didn't mean the entire file. Just the ArtifactPath and createArtifactDir

File: cmd/check_operator.go [hunk 7]
```diff
@@ -56,11 +56,10 @@ var checkOperatorCmd = &cobra.Command{
 		// create the results file early to catch cases where we are not
 		// able to write to the filesystem before we attempt to execute checks.
 		resultsFile, err := os.OpenFile(
-			filepath.Join(viper.GetString("artifacts"), resultsFilenameWithExtension(formatter.FileExtension())),
+			filepath.Join(fileutils.ArtifactPath(""), resultsFilenameWithExtension(formatter.FileExtension())),
```
Comment (bcrochet) [inline cmd/check_operator.go:59]: ArtifactPath doesn't take an argument

**Review by bcrochet — CHANGES_REQUESTED** [review]
Please limit the PR to a single commit

File: certification/internal/engine/engine.go (hunk 5 above)
Comment (rocrisp) [reply certification/internal/engine/engine.go:16]: Done!

File: certification/internal/utils/file/helper.go (hunk 6 above)
Comment (rocrisp) [reply certification/internal/utils/file/helper.go:1]: Gotcha! Fixed.

File: cmd/check_operator.go (hunk 7 above)
Comment (rocrisp) [reply cmd/check_operator.go:59]: Fixed.

Comment (rocrisp) [reply cmd/check_operator.go]: Fixed.

**Review by bcrochet — CHANGES_REQUESTED** [review]
Looks good, but should only be a single commit. Please squash.

**Comment by rocrisp** [comment]
Oh wait, the squash messed up my changes.

**Review by bcrochet — APPROVED** [review]
/lgtm

**Review by samira-barouti — APPROVED** [review]

**Review by skattoju — APPROVED** [review]
