### PR TITLE
Remove tag from container when listing tags

### LINKED ISSUE #290: HasUniqueTag errors when checking a properly tagged ubi8 image
## Bug Description
`HasUniqueTag` errors when checking a properly tagged ubi8 image.

## Version and Command Invocation
preflight version 0.0.0 <commit: 406f54f7aba2c59f5d79b5a10031af415b7c66bc>

## Steps to Reproduce:
(How can we reproduce this?)
1) `$ preflight check container registry.access.redhat.com/ubi8:8.4`

## Expected Result
I'd expect the `BasedOnUbi` check to PASS

## Actual Result
```bash
$ PFLT_LOGLEVEL=trace ./preflight check container registry.access.redhat.com/ubi8:8.4
time="2021-10-07T15:47:47-05:00" level=info msg="config file not found, proceeding without it"
time="2021-10-07T15:47:47-05:00" level=info msg="certification library version 0.0.0 <commit: 406f54f7aba2c59f5d79b5a10031af415b7c66bc>"
time="2021-10-07T15:47:47-05:00" level=info msg="target image: registry.access.redhat.com/ubi8:8.4"
time="2021-10-07T15:47:47-05:00" level=info msg="pulling image from target registry"
time="2021-10-07T15:47:48-05:00" level=debug msg="temporary directory is /var/folders/1m/51t9hzss67s18576kw_5_l1w0000gn/T/preflight-3625040718"
time="2021-10-07T15:47:48-05:00" level=debug msg="exporting and flattening image"
time="2021-10-07T15:47:48-05:00" level=debug msg="extracting container filesystem to /var/folders/1m/51t9hzss67s18576kw_5_l1w0000gn/T/preflight-3625040718/fs"
time="2021-10-07T15:47:48-05:00" level=debug msg="writing container filesystem to output dir/var/folders/1m/51t9hzss67s18576kw_5_l1w0000gn/T/preflight-3625040718/fs"
time="2021-10-07T15:47:58-05:00" level=info msg="executing checks"
time="2021-10-07T15:47:58-05:00" level=info msg="running check: LayerCountAcceptable"
time="2021-10-07T15:47:58-05:00" level=debug msg="detected 2 layers in image"
time="2021-10-07T15:47:58-05:00" level=info msg="check completed: LayerCountAcceptable" result=PASSED
time="2021-10-07T15:47:58-05:00" level=info msg="running check: HasNoProhibitedPackagesMounted"
time="2021-10-07T15:47:58-05:00" level=info msg="check completed: HasNoProhibitedPackagesMounted" result=PASSED
time="2021-10-07T15:47:58-05:00" level=info msg="running check: HasRequiredLabel"
time="2021-10-07T15:47:58-05:00" level=info msg="check completed: HasRequiredLabel" result=PASSED
time="2021-10-07T15:47:58-05:00" level=info msg="running check: RunAsNonRoot"
time="2021-10-07T15:47:58-05:00" level=debug msg="detected empty user. Presumed to be running as root"
time="2021-10-07T15:47:58-05:00" level=info msg="check completed: RunAsNonRoot" result=FAILED
time="2021-10-07T15:47:58-05:00" level=info msg="running check: BasedOnUbi"
time="2021-10-07T15:47:58-05:00" level=info msg="check completed: BasedOnUbi" result=PASSED
time="2021-10-07T15:47:58-05:00" level=info msg="running check: HasLicense"
time="2021-10-07T15:47:58-05:00" level=error msg="Error when checking for /licenses : stat /var/folders/1m/51t9hzss67s18576kw_5_l1w0000gn/T/preflight-3625040718/fs/licenses: no such file or directory"
time="2021-10-07T15:47:58-05:00" level=info msg="check completed: HasLicense" result=FAILED
time="2021-10-07T15:47:58-05:00" level=info msg="running check: HasUniqueTag"
time="2021-10-07T15:47:58-05:00" level=info msg="check completed: HasUniqueTag" ERROR="parsing repo \"registry.access.redhat.com/ubi8:8.4\": repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: ubi8:8.4" result="parsing repo \"registry.access.redhat.com/ubi8:8.4\": repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: ubi8:8.4"
```
```json
{
    "image": "registry.access.redhat.com/ubi8:8.4",
    "passed": false,
    "test_library": {
        "name": "github.com/redhat-openshift-ecosystem/openshift-preflight",
        "version": "0.0.0",
        "commit": "406f54f7aba2c59f5d79b5a10031af415b7c66bc"
    },
    "results": {
        "passed": [
            {
                "name": "LayerCountAcceptable",
                "description": "Checking if container has less than 40 layers.  Too many layers within the container images can degrade container performance."
            },
            {
                "name": "HasNoProhibitedPackagesMounted",
                "elapsed_time": 110,
                "description": "Checks to ensure that the image in use does not include prohibited packages, such as Red Hat Enterprise Linux (RHEL) kernel packages."
            },
            {
                "name": "HasRequiredLabel",
                "elapsed_time": 102,
                "description": "Checking if the required labels (name, vendor, version, release, summary, description) are present in the container metadata."
            },
            {
                "name": "BasedOnUbi",
                "elapsed_time": 1,
                "description": "Checking if the container's base image is based upon the Red Hat Universal Base Image (UBI)"
            }
        ],
        "failed": [
            {
                "name": "RunAsNonRoot",
                "description": "Checking if container runs as the root user because a container that does not specify a non-root user will fail the automatic certification, and will be subject to a manual review before the container can be approved for publication",
                "help": "Check RunAsNonRoot encountered an error. Please review the preflight.log file for more information.",
                "suggestion": "Indicate a specific USER in the dockerfile or containerfile",
                "knowledgebase_url": "https://connect.redhat.com/zones/containers/container-certification-policy-guide",
                "check_url": "https://connect.redhat.com/zones/containers/container-certification-policy-guide"
            },
            {
                "name": "HasLicense",
                "description": "Checking if terms and conditions applicable to the software including open source licensing information are present. The license must be at /licenses",
                "help": "Check HasLicense encountered an error. Please review the preflight.log file for more information.",
                "suggestion": "Create a directory named /licenses and include all relevant licensing and/or terms and conditions as text file(s) in that directory.",
                "knowledgebase_url": "https://connect.redhat.com/zones/containers/container-certification-policy-guide",
                "check_url": "https://connect.redhat.com/zones/containers/container-certification-policy-guide"
            }
        ],
        "errors": [
            {
                "name": "HasUniqueTag",
                "description": "Checking if container has a tag other than 'latest', so that the image can be uniquely identified.",
                "help": "Check HasUniqueTag encountered an error. Please review the preflight.log file for more information."
            }
        ]
    }
}
```

## Additional Context
(Anything else you think might help us troubleshoot, like your platform, dependency versions, etc).

### PR DESCRIPTION
**Pull request by bcrochet**
When listing tags from a remote repository, Crane will throw an error if there
is already a tag on the URI (which makes sense, as we're trying to get a list
of tags!). This strips the tag before passing to Crane. Adds a unit test for
this.

Fixes #290

Signed-off-by: Brad P. Crochet <brad@redhat.com>

### CODE REVIEW

File: certification/internal/policy/container/has_unique_tag.go [hunk 1]
```diff
@@ -19,7 +19,8 @@ type HasUniqueTagCheck struct {
 }
 
 func (p *HasUniqueTagCheck) Validate(imgRef certification.ImageReference) (bool, error) {
-	tags, err := p.getDataToValidate(imgRef.ImageURI)
+	uriWithoutTags := strings.Split(imgRef.ImageURI, ":")[0]
```
Comment (samira-barouti) [inline certification/internal/policy/container/has_unique_tag.go:22]: I think this won't work if the image is pinned with the SHA tag.

**Review by samira-barouti — CHANGES_REQUESTED** [review]

File: certification/internal/policy/container/has_unique_tag.go (hunk 1 above)
Comment (komish) [reply certification/internal/policy/container/has_unique_tag.go:22]: I thought we had some logic for extracting the basename of the image (e.g. without tag or digest) at some point in time.

Comment (samira-barouti) [reply certification/internal/policy/container/has_unique_tag.go:22]: It was part of the SkopeoEngine logic that has been removed.
