### PR TITLE
Move the scorecard checks to use the crane engine

### LINKED ISSUE #165: Preflight running in a container should not require privilege
## Bug Description
Preflight when run in a container currently requires a privileged container. This should not be the case.

### PR DESCRIPTION
**Pull request by bcrochet**
The scorecard checks were already enabled, but still pulling an image via podman. This now just uses the on-disk bundle.

Depends-on: #188 
Fixes #165 

Signed-off-by: Brad P. Crochet <brad@redhat.com>

### CODE REVIEW

File: certification/engine/operatorsdk.go [hunk 1]
```diff
@@ -0,0 +1,184 @@
...
+	if opts.ServiceAccount != "" {
+		cmdArgs = append(cmdArgs, "--service-account", opts.ServiceAccount)
+	}
+
+	configFile, err := createScorecardConfigFile()
+	if err != nil {
+		log.Error("could not create scorecard config file", err)
+		return nil, err
+	}
+	defer os.Remove(configFile)
```
Comment (samira-barouti) [inline certification/engine/operatorsdk.go:51]: I think the defer statement should be placed right after line 46. Otherwise if an error occurred while executing `createScorecardConfigFile`, the Scorecard method returns and the execution will never reach this line to push the deferred method to the stack.

File: certification/internal/policy/operator/scorecard_basic_check_spec.go [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+const scorecardBasicCheckResult string = "operator_bundle_scorecard_BasicSpecCheck.json"
+
+func NewScorecardBasicSpecCheck(operatorSdkEngine *cli.OperatorSdkEngine) *ScorecardBasicSpecCheck {
+	return &ScorecardBasicSpecCheck{
+		scorecardCheck{OperatorSdkEngine: *operatorSdkEngine},
+	}
+}
+
+func (p *ScorecardBasicSpecCheck) Validate(bundleRef certification.ImageReference) (bool, error) {
+	log.Debug("Running operator-sdk scorecard check for ", bundleRef.ImageFSPath)
```
Comment (samira-barouti) [inline certification/internal/policy/operator/scorecard_basic_check_spec.go:24]: I think we want to print bundleRef.ImageURI.

File: certification/engine/operatorsdk.go [hunk 3]
```diff
@@ -0,0 +1,184 @@
...
+	cmdArgs = append(cmdArgs, "--config", configFile)
+	cmdArgs = append(cmdArgs, "--verbose")
```
Comment (samira-barouti) [inline certification/engine/operatorsdk.go:53]: I suggest for the sake of consistency, we follow the same path as BundleValidate and let the caller method set a `verbosity` option.

**Review by acornett21 — APPROVED** [review]

File: certification/engine/operatorsdk.go [hunk 4]
```diff
@@ -0,0 +1,188 @@
...
+		cmdArgs = append(cmdArgs, "--namespace", opts.Namespace)
+	}
+	if opts.ServiceAccount != "" {
+		cmdArgs = append(cmdArgs, "--service-account", opts.ServiceAccount)
+	}
+
+	configFile, err := createScorecardConfigFile()
+	if configFile != "" {
+		defer os.Remove(configFile)
+	}
```
Comment (samira-barouti) [inline certification/engine/operatorsdk.go:49]: Just did a quick test and it seems os.Remove returns an error that the directory does not exist. I think you can remove the if block and ignore the returned error.

**Review by samira-barouti — APPROVED** [review]
Just a little nit

File: certification/engine/operatorsdk.go [hunk 5]
```diff
@@ -0,0 +1,188 @@
+package engine
```
Comment (samira-barouti) [inline certification/engine/operatorsdk.go:1]: This is probably a broader discussion on the code design: we have two engine directories atm; I believe we should be more prescriptive about which one should be used for the preflight internal. My intuition is to use the certification/internal/engine for everything which is internal to preflight (such as operatorsdk, openshift, crane) and let the certification/engine be for the check engine. I would like to hear everyone's feedback on this matter. 

@komish @bcrochet @acornett21 @jomkz

File: certification/engine/operatorsdk.go (hunk 4 above)
Comment (bcrochet) [reply certification/engine/operatorsdk.go]: This will be handled in #188

File: certification/engine/operatorsdk.go (hunk 5 above)
Comment (bcrochet) [reply certification/engine/operatorsdk.go]: I will test whether this can continue to live in the internal directory. If that's the case, then it's probably a moot point, and I'll just leave it there.

Comment (bcrochet) [reply certification/engine/operatorsdk.go]: And... it can. I'll move this to internal.

**Review by samira-barouti — APPROVED** [review]
/lgtm
