### PR TITLE
Increase the default wait time for scorecard tests

### LINKED ISSUE #329: Random failure of ScorecardBasicSpecCheck test
## Bug Description
Sometimes ScorecardBasicSpecCheck randomly fails, in ~30% of tests.
This fail seems to be preflight-related because `operator-sdk scorecard --selector=test=basic-check-spec-test` which runs just after always showing "pass". The error on the preflight side is `error running tests context deadline exceeded`, so maybe it's something timeout-related. 

results.json:
```
    "errors": [
      {
        "name": "ScorecardBasicSpecCheck",
        "elapsed_time": 30130,
        "description": "Check to make sure that all CRs have a spec block.",
        "help": "Check ScorecardBasicSpecCheck encountered an error. Please review the artifacts/operator_bundle_scorecard_BasicSpecCheck.json file for more information."
      },
```

File `artifacts/operator_bundle_scorecard_BasicSpecCheck.json` is absent (issue #169 ).

preflight.log:
```
time="2021-11-04T10:24:50Z" level=info msg="running check: ScorecardBasicSpecCheck"
time="2021-11-04T10:24:50Z" level=debug msg="Running operator-sdk scorecard check for quay.io/rh-nfv-int/testpmd-operator-bundle@sha256:5e28f883faacefa847104ebba1a1a22ee897b7576f0af6b8253c68b5c8f42815"
time="2021-11-04T10:24:50Z" level=debug msg="--selector=[test=basic-check-spec-test]"
time="2021-11-04T10:24:50Z" level=trace msg="running scorecard with the following invocation[operator-sdk scorecard --output json --selector=test=basic-check-spec-test --kubeconfig /kubeconfig --namespace preflight-testing --service-account default --config /tmp/scorecard-test-config-1574852032.yaml --verbose /tmp/preflight-4104845048/fs]"
time="2021-11-04T10:25:20Z" level=error msg="stdout: "
time="2021-11-04T10:25:20Z" level=error msg="stderr: time=\"2021-11-04T10:24:50Z\" level=debug msg=\"Debug logging is set\"\nError: error running tests context deadline exceeded\nUsage:\n  operator-sdk scorecard [flags]\n\nFlags:\n  -c, --config string            path to scorecard config file\n  -h, --help                     help for scorecard\n      --kubeconfig string        kubeconfig path\n  -L, --list                     Option to enable listing which tests are run\n  -n, --namespace string         namespace to run the test images in\n  -o, --output string            Output format for results. Valid values: text, json, xunit (default \"text\")\n  -l, --selector string          label selector to determine which tests are run\n  -s, --service-account string   Service account to use for tests (default \"default\")\n  -x, --skip-cleanup             Disable resource cleanup after tests are run\n  -b, --storage-image string     Storage image to be used by the Scorecard pod (default \"docker.io/library/busybox@sha256:c71cb4f7e8ececaffb34037c2637dc86820e4185100e18b4d02d613a9bd772af\")\n  -t, --test-output string       Test output directory. (default \"test-output\")\n  -u, --untar-image string       Untar image to be used by the Scorecard pod (default \"registry.access.redhat.com/ubi8@sha256:910f6bc0b5ae9b555eb91b88d28d568099b060088616eba2867b07ab6ea457c7\")\n  -w, --wait-time duration       seconds to wait for tests to complete. Example: 35s (default 30s)\n\nGlobal Flags:\n      --plugins strings   plugin keys to be used for this subcommand execution\n      --verbose           Enable verbose logging\n\ntime=\"2021-11-04T10:25:20Z\" level=fatal msg=\"error running tests context deadline exceeded\"\n"
time="2021-11-04T10:25:20Z" level=info msg="check completed: ScorecardBasicSpecCheck" ERROR="failed to run operator-sdk scorecard: exit status 1" result="failed to run operator-sdk scorecard: exit status 1"
```

operator-sdk scorecard output:
```
{
  "kind": "TestList",
  "apiVersion": "scorecard.operatorframework.io/v1alpha3",
  "items": [
    {
      "kind": "Test",
      "apiVersion": "scorecard.operatorframework.io/v1alpha3",
      "spec": {
        "image": "quay.io/operator-framework/scorecard-test@sha256:66023c1e0f6021407811fb2b1d42aa16af6f41f2c791b2bdeb6ba696d000cf5d",
        "entrypoint": [
          "scorecard-test",
          "basic-check-spec"
        ],
        "labels": {
          "suite": "basic",
          "test": "basic-check-spec-test"
        },
        "storage": {
          "spec": {
            "mountPath": {}
          }
        }
      },
      "status": {
        "results": [
          {
            "name": "basic-check-spec",
            "state": "pass",
            "creationTimestamp": null
          }
        ]
      }
    }
  ]
}
```

## Version and Command Invocation
1.0.3

## Steps to Reproduce:
Run `preflight operator check` for testpmd operator several times in a row:
```
image: 'quay.io/rh-nfv-int/testpmd-operator-bundle@sha256:5e28f883faacefa847104ebba1a1a22ee897b7576f0af6b8253c68b5c8f42815',
index_image: 'quay.io/tkrishtop/index-testpmd-operator-bundle:v0.2.9'
```

[Sometimes ScorecardBasicSpecCheck fails (~30%)](https://www.distributed-ci.io/jobs/bd69b770-4461-41f9-a44f-a01680b9c78b/files)

and [sometimes pass (~70%)](https://www.distributed-ci.io/jobs/6e57d051-636a-40f0-8846-b7ba277db5a6/files)

## Expected Result
ScorecardBasicSpecCheck should always pass

## Actual Result
[Sometimes ScorecardBasicSpecCheck fails (~30%)](https://www.distributed-ci.io/jobs/bd69b770-4461-41f9-a44f-a01680b9c78b/files)

and [sometimes pass (~70%)](https://www.distributed-ci.io/jobs/6e57d051-636a-40f0-8846-b7ba277db5a6/files)

### PR DESCRIPTION
**Pull request by samira-barouti**
* Fixes #329

This PR introduces a new field for the scorecard runtime configuration.
Scorecard requires pulling the busybox image (among others). The default
wait time of 30s is not enough to pull the dependencies and run the check.
This PR increases the wait time to 120s.

Found a relevant issue on github:
https://github.com/operator-framework/operator-sdk/issues/4148

### CODE REVIEW

File: certification/internal/policy/operator/scorecard_check.go [hunk 1]
```diff
@@ -42,6 +42,7 @@ func (p *scorecardCheck) getDataToValidate(bundleImage string, selector []string
 		Namespace:      namespace,
 		ServiceAccount: serviceAccount,
 		Verbose:        true,
+		WaitTime:       "120s",
```
Comment (bcrochet) [inline certification/internal/policy/operator/scorecard_check.go:45]: This just means it will wait up to 120s, not that it will wait 120s no matter what, right? If the former, I'm fine with this. If the latter, can we maybe start with 2x the default and see if that helps?

**Review by jomkz — APPROVED** [review]
/lgtm

**Review by bcrochet — COMMENTED** [review]
Quick question, otherwise LGTM.

File: certification/internal/policy/operator/scorecard_check.go (hunk 1 above)
Comment (acornett21) [reply certification/internal/policy/operator/scorecard_check.go:45]: This is from their `help` menu, not sure if it provides more clarity or not.
`-w, --wait-time duration       seconds to wait for tests to complete. Example: 35s (default 30s)`

Comment (samira-barouti) [reply certification/internal/policy/operator/scorecard_check.go:45]: @bcrochet @acornett21 it is the former; it will wait up to 120s.

**Review by acornett21 — APPROVED** [review]

**Review by bcrochet — APPROVED** [review]
/lgtm
